services:
  - type: web
    name: secure-file-sharing
    env: node
    buildCommand: cd renderFiles && npm install
    startCommand: cd renderFiles && node server.js
    #envVars:
    #  - key: MONGO_URI
    #    value: "your_mongo_connection_string"
    #  - key: SECRET_KEY
    #    value: "your_secret_key"
